from pathlib import Path

import pytest
from alembic.config import Config

from alembic import command
from app.core.config import settings

BACKEND = Path(__file__).resolve().parents[1]


def test_migrations_match_the_models(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Fails when a model changes without a matching Alembic migration."""
    monkeypatch.setattr(settings, "DATABASE_URL", f"sqlite+aiosqlite:///{tmp_path / 'migrations.db'}")
    config = Config(str(BACKEND / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND / "alembic"))

    command.upgrade(config, "head")
    command.check(config)  # raises AutogenerateDiffsDetected on drift
    command.downgrade(config, "base")
